set -g extended-keys on
set -g mouse on

# Fix nvim background color
set -as terminal-features ",xterm-256color:RGB"

# Easier navigation in copy mode
setw -g mode-keys vi
bind -T copy-mode-vi C-u send-keys -X halfpage-up
bind -T copy-mode-vi C-d send-keys -X halfpage-down
bind -n M-k copy-mode

